Repository EmirhanDemirci/Typo, pull requests merged in 2019-11, with the labels that each got.

#8 Onzin zal erin komen.
  Typo/Views/Home/About.cshtml
Labels: bug, documentation, duplicate, enhancement, good first issue, help wanted, invalid, question, wontfix

#10 Dat was niet lief extra
  Typo/Views/Home/About.cshtml
Labels: enhancement

#11 Get back to origin
  Typo/Views/Home/About.cshtml
Labels: invalid

#12 DB Connection
  Typo/appsettings.json
Labels: enhancement

#13 About aangepast
  Typo/Views/Home/About.cshtml
Labels: help wanted

#15 Login Complete
  Typo/Controllers/AccountController.cs
  Typo/Models/Account.cs
  Typo/Views/Account/Login.cshtml
  Typo/Views/Shared/_Layout.cshtml
Labels: enhancement

#16 Website changed
  Typo/Controllers/GameController.cs
  Typo/Startup.cs
  Typo/Views/Account/Login.cshtml
  Typo/Views/Account/Register.cshtml
  Typo/Views/Game/TypeRacer.cshtml
  Typo/Views/Home/Contact.cshtml
  Typo/Views/Home/Index.cshtml
  Typo/Views/Shared/_Layout.cshtml
  Typo/wwwroot/css/site.css
Labels: enhancement

#17 Profile class
  Typo/Models/Profile.cs
Labels: enhancement

#18 Architecture
  Logic/Class1.cs
  Logic/Properties/AssemblyInfo.cs
  Logic/Typo.Logic.csproj
  Typo.Dal/Sql/Connection.cs
  Typo.Dal/Typo.Dal.csproj
  Typo.Model/Models/Account.cs
  Typo.Model/Models/ErrorViewModel.cs
  Typo.Model/Typo.Model.csproj
  Typo.sln
  Typo/Controllers/AccountController.cs
  Typo/Controllers/HomeController.cs
  Typo/Models/Account.cs
  Typo/Startup.cs
  Typo/Typo.csproj
  Typo/Views/Account/Login.cshtml
  Typo/Views/Account/Register.cshtml
  Typo/Views/Shared/Error.cshtml
  Typo/Views/Shared/_Layout.cshtml
  Typo/Views/_ViewImports.cshtml
Labels: enhancement

#22 Score class en method
  Typo.Dal/Database/ScoreSQL.cs
  Typo.Dal/Typo.Dal.csproj
  Typo.Logic/Services/ScoreService.cs
  Typo.Logic/Typo.Logic.csproj
  Typo.Model/Models/Score.cs
  Typo.Model/Typo.Model.csproj
  Typo/Controllers/ScoreController.cs
  Typo/Models/Score.cs
  Typo/Typo.csproj
  Typo/Views/Score/ScoreCheck.cshtml
  Typo/Views/Score/ScoreInput.cshtml
  Typo2/Controllers/ScoreController.cs
  Typo2/Typo.csproj
  Typo2/Views/Score/ScoreInput.cshtml
  Typo2/Views/Score/ScoreTake.cshtml
Labels: enhancement
